Prepare TDLib update

diff --git a/.github/patches/ios-arm64.patch b/.github/patches/ios-arm64.patch
--- a/.github/patches/ios-arm64.patch
+++ b/.github/patches/ios-arm64.patch
@@ -18,6 +18,15 @@ diff --git a/td/example/ios/build-openssl.sh b/td/example/ios/build-openssl.sh
    fi
  
    for simulator in $simulators;
+@@ -25,7 +25,7 @@ do
+     echo $platform
+     cd Python-Apple-support
+     #NB: -j will fail
+-    SOURCE_DATE_EPOCH=1 ZERO_AR_DATE=1 make OpenSSL-$platform || exit 1
++    SOURCE_DATE_EPOCH=1 ZERO_AR_DATE=1 make OpenSSL-$platform TARGETS-iOS=iphoneos.arm64 || exit 1
+     cd ..
+     rm -rf third_party/openssl/$platform || exit 1
+     mkdir -p third_party/openssl/$platform/lib || exit 1
 diff --git a/td/example/ios/build.sh b/td/example/ios/build.sh
 --- a/td/example/ios/build.sh
 +++ b/td/example/ios/build.sh
diff --git a/.github/patches/ios-x64-simulator.patch b/.github/patches/ios-x64-simulator.patch
--- a/.github/patches/ios-x64-simulator.patch
+++ b/.github/patches/ios-x64-simulator.patch
@@ -1,53 +1,3 @@
-diff --git a/td/example/ios/Python-Apple-support.patch b/td/example/ios/Python-Apple-support.patch
---- a/td/example/ios/Python-Apple-support.patch
-+++ b/td/example/ios/Python-Apple-support.patch
-@@ -1,5 +1,4 @@
- diff --git a/Makefile b/Makefile
--index a1d13e9..8efcf20 100644
- --- a/Makefile
- +++ b/Makefile
- @@ -18,8 +18,13 @@
-@@ -44,7 +43,7 @@ index a1d13e9..8efcf20 100644
-  CFLAGS-iOS=-mios-version-min=$(VERSION_MIN-iOS)
-  
- +# iOS-simulator targets
--+TARGETS-iOS-simulator=iphonesimulator.x86_64 iphonesimulator.arm64
-++TARGETS-iOS-simulator=iphonesimulator.x86_64
- +CFLAGS-iOS-simulator=-mios-simulator-version-min=$(VERSION_MIN-iOS)
- +
-  # tvOS targets
-@@ -79,7 +78,7 @@ index a1d13e9..8efcf20 100644
-  # The architecture of the machine doing the build
-  HOST_ARCH=$(shell uname -m)
-  HOST_PYTHON=install/macOS/macosx/python-$(PYTHON_VERSION)
--@@ -212,6 +236,10 @@ ARCH-$(target)=$$(subst .,,$$(suffix $(target)))
-+@@ -212,6 +236,12 @@ ARCH-$(target)=$$(subst .,,$$(suffix $(target)))
-  
-  ifeq ($(os),macOS)
-  TARGET_TRIPLE-$(target)=$$(ARCH-$(target))-apple-darwin
-@@ -87,10 +86,12 @@ index a1d13e9..8efcf20 100644
- +TARGET_TRIPLE-$(target)=$$(ARCH-$(target))-apple-xros
- +else ifeq ($(os),visionOS-simulator)
- +TARGET_TRIPLE-$(target)=$$(ARCH-$(target))-apple-xros-simulator
-++else ifeq ($(os),iOS-simulator)
-++TARGET_TRIPLE-$(target)=$$(ARCH-$(target))-apple-ios-simulator
-  else
-  	ifeq ($$(findstring simulator,$$(SDK-$(target))),)
-  TARGET_TRIPLE-$(target)=$$(ARCH-$(target))-apple-$$(OS_LOWER-$(target))
--@@ -662,7 +690,7 @@ BZIP2_FATLIB-$(sdk)=$$(BZIP2_MERGE-$(sdk))/lib/libbz2.a
-+@@ -662,7 +692,7 @@ BZIP2_FATLIB-$(sdk)=$$(BZIP2_MERGE-$(sdk))/lib/libbz2.a
-  XZ_MERGE-$(sdk)=$(PROJECT_DIR)/merge/$(os)/$(sdk)/xz-$(XZ_VERSION)
-  XZ_FATLIB-$(sdk)=$$(XZ_MERGE-$(sdk))/lib/liblzma.a
-  
-@@ -99,7 +100,7 @@ index a1d13e9..8efcf20 100644
-  OPENSSL_FATINCLUDE-$(sdk)=$$(OPENSSL_MERGE-$(sdk))/include
-  OPENSSL_SSL_FATLIB-$(sdk)=$$(OPENSSL_MERGE-$(sdk))/lib/libssl.a
-  OPENSSL_CRYPTO_FATLIB-$(sdk)=$$(OPENSSL_MERGE-$(sdk))/lib/libcrypto.a
--@@ -716,14 +744,14 @@ $$(OPENSSL_SSL_FATLIB-$(sdk)): $$(foreach target,$$(SDK_TARGETS-$(sdk)),$$(OPENS
-+@@ -716,14 +746,14 @@ $$(OPENSSL_SSL_FATLIB-$(sdk)): $$(foreach target,$$(SDK_TARGETS-$(sdk)),$$(OPENS
-  	mkdir -p $$(OPENSSL_MERGE-$(sdk))/lib
-  	lipo -create -output $$@ \
-  		$$(foreach target,$$(SDK_TARGETS-$(sdk)),$$(OPENSSL_SSL_LIB-$$(target))) \
 diff --git a/td/example/ios/build-openssl.sh b/td/example/ios/build-openssl.sh
 --- a/td/example/ios/build-openssl.sh
 +++ b/td/example/ios/build-openssl.sh
@@ -68,6 +18,15 @@ diff --git a/td/example/ios/build-openssl.sh b/td/example/ios/build-openssl.sh
    fi
  
    for simulator in $simulators;
+@@ -25,7 +25,7 @@ do
+     echo $platform
+     cd Python-Apple-support
+     #NB: -j will fail
+-    SOURCE_DATE_EPOCH=1 ZERO_AR_DATE=1 make OpenSSL-$platform || exit 1
++    SOURCE_DATE_EPOCH=1 ZERO_AR_DATE=1 make OpenSSL-$platform TARGETS-iOS-simulator=iphonesimulator.x86_64 || exit 1
+     cd ..
+     rm -rf third_party/openssl/$platform || exit 1
+     mkdir -p third_party/openssl/$platform/lib || exit 1
 diff --git a/td/example/ios/build.sh b/td/example/ios/build.sh
 --- a/td/example/ios/build.sh
 +++ b/td/example/ios/build.sh
